requirejs.config({
    baseUrl: '/',
    deps: [
        'lxk.fef',
        'angular',
        'angular-resource',
        'angular-route',
        'app',
        'routes',
        'user',
        'user.factory',
        'service-request',
        'service-request.factory',
        'service-request.directives',
        'address',
        'address.controller',
        'address.directives',
        'address.factory',
        'contact',
        'contact.controller',
        'contact.directives',
        'contact.factory'
    ],
    shim: {
        'angular-resource': ['angular'],
        'angular-route': ['angular'],
        'app': ['angular', 'angular-resource', 'angular-route'],
        'routes': ['app'],
        'user': ['app'],
        'user.factory': ['app', 'user'],
        'user.directives': ['app', 'user'],
        'service-request': ['app'],
        'service-request.factory': ['app', 'service-request'],
        'service-request.directives': ['app', 'service-request'],
        'address': ['app'],
        'address.controller': ['app', 'address', 'address.factory', 'contact.factory'],
        'address.directives': ['app', 'address'],
        'address.factory': ['app', 'address', 'service-request.factory'],
        'contact': ['app'],
        'contact.controller': ['app', 'contact', 'contact.factory'],
        'contact.directives': ['app', 'contact'],
        'contact.factory': ['app', 'contact']
    },
    paths: {
        'lxk.fef': 'etc/lxk-framework/js/lxk-framework.min',
        'angular': 'js/libs/angular.min',
        'angular-resource': 'js/libs/angular-resource.min',
        'angular-route': 'js/libs/angular-route.min',
        'app': 'js/app',
        'routes': 'js/routes',
        'user': 'js/users/user',
        'user.factory': 'js/users/usersFactory',
        'service-request': 'js/service_requests/serviceRequest',
        'service-request.factory': 'js/service_requests/serviceRequestsFactory',
        'service-request.directives': 'js/service_requests/directives',
        'address': 'js/address_service_requests/addressServiceRequest',
        'address.controller': 'js/address_service_requests/controller',
        'address.directives': 'js/address_service_requests/directives',
        'address.factory': 'js/address_service_requests/addressesFactory',
        'contact': 'js/contact_service_requests/contactServiceRequest',
        'contact.controller': 'js/contact_service_requests/controller',
        'contact.directives': 'js/contact_service_requests/directives',
        'contact.factory': 'js/contact_service_requests/contactsFactory'
    },
    map: {
        "*": {
            "jquery": "jquery-private",
            "stable": "modules"
        },
        "jquery-private": {"jquery": "jquery"}
    },
    bundles: {
        "lxk.fef": [
            "jquery",
            "fef.jquery",
            "jquery-private",
            "throttle-debounce",
            "modernizr",
            "variables",
            "modules/alerts",
            "modules/banner",
            "modules/breadcrumb",
            "modules/card",
            "modules/carousel",
            "modules/custom-input",
            "modules/dropdown",
            "modules/form-selectbox",
            "modules/form",
            "modules/griddy",
            "modules/media-queries",
            "modules/modal",
            "modules/modalmanager",
            "modules/quote",
            "modules/rail-nav",
            "modules/responsive-images",
            "modules/responsive-tables",
            "modules/set",
            "modules/sifter",
            "modules/slide-in-panel"
        ]
    }
});
