requirejs.config({
    baseUrl: '/',
    deps: [
        'lxk.fef',
        'app'
    ],
    shim: {
        'angular': {exports: 'angular'},
        'angular-resource': ['angular'],
        'angular-route': ['angular'],
        'angular-cookies': ['angular'],
        'angular-translate': ['angular'],
        'angular-translate-storage-cookie': ['angular-translate'],
        'angular-translate-storage-local': ['angular-translate'],
        'angular-translate-loader-static-files': ['angular-translate'],
        'angular-translate-loader-url': ['angular-translate'],
        'angular-spring-data-rest': ['angular-resource'],

        'pdfMakeLib': {
            exports: 'pdfMake'
        },
        'pdfmake': {
            deps: ['pdfMakeLib'],
            exports: 'pdfMake'
        },
        'angular-sanitize': ['angular'],
        'app': [
            'angular-gatekeeper',

            'hateoasFactory',
            'hateoasFactory.serviceFactory',

            'queue',
            'queue.directives',
            'queue.queueNotificationController',
            'queue.queueListController',
            'queue.tombstoneFactory',

            

            'dashboard',
            'dashboard.dashboardController',

            'ngTagsInput',

            'library',
            'library.libraryFactory',
            'library.libraryTagFactory',
            'library.libraryOwnerFactory',
            'library.libraryListController',
            'library.libraryTagController',
            'library.libraryController',
            'library.libraryDeleteInlineController',
            'library.libraryViewController',

            'nav',
            'nav.navController',
            'nav.navFactory',
            'nav.navItemFactory',
            'nav.directives',

            'rome',

            'address',
            'address.addressAddController',
            'address.addressUpdateController',
            'address.addressDeleteController',
            'address.addressController',
            'address.addressListController',
            'address.directives',
            'address.factory',

            'form',
            'form.datePicker',
            'form.directives',

            'account',
            'account.accountFactory',
            'account.roleFactory',
            'account.accountController',

            'notification',
            'notification.notificationFactory',
            'notification.notificationController',
            'notification.directives',
            'notification.createNotificationController',
            'notification.manageNotificationController',

            'siebel',
            'siebel.siebelFactory',
            'siebel.siebelListController',
            'siebel.directives',
            'siebel.createSiebelValueController',
            'siebel.manageSiebelValueController',

            'user',
            'user.factory',
            'user.userInfoFactory',
            'user.impersonateFactory',
            'user.userAdministrationFactory',
            'user.lexmarkUserFactory',
            'user.roleFactory',
            'user.allAccountFactory',
            'user.directives',
            'user.userController',
            'user.userAddController',
            'user.lexmarkUserAddController',
            'user.lexmarkUserListController',
            'user.impersonateUserListController',
            'user.usersController',
            'user.userTabController',
            'user.manageUserTabController',
            'user.manageUserController',
            'user.invitedUserController',

            'report',
            'report.reportController',
            'report.reportListController',
            'report.reportFinderController',
            'report.directives',
            'report.factory',

            'tree',
            'tree.treeItemsService',
            'tree.treeController',
            'tree.treeItemController',
            'tree.directives'
        ],

        'googlecharting': ['angular'],

        'rome': ['angular'],

        'ngTagsInput': ['angular'],

        'queue': ['angular'],
        'queue.directives': ['angular', 'queue'],
        'queue.queueNotificationController': ['angular', 'queue'],
        'queue.queueListController': ['angular', 'queue'],
        'queue.tombstoneFactory': ['angular', 'queue'],

        'form':['angular', 'lxk.fef'],
        'form.datePicker' : ['form'],
        'form.directives': ['form'],

        'account': ['angular'],
        'account.accountFactory': ['account'],
        'account.roleFactory': ['account'],
        'account.accountController': ['account'],

        'library': ['angular'],
        'library.libraryListController': ['library'],
        'library.libraryController': ['library'],
        'library.libraryDeleteInlineController': ['library'],
        'library.libraryViewController': ['library'],
        'library.libraryTagController': ['library'],
        'library.libraryFactory': ['library'],
        'library.libraryTagFactory': ['library'],
        'library.libraryOwnerFactory': ['library'],
        'library.directives': ['library'],

        'user': ['angular', 'utility.urlHelper'],
        'user.factory': ['user'],
        'user.impersonateFactory': ['user'],
        'user.userInfoFactory': ['user'],
        'user.allAccountFactory': ['user'],
        'user.userAdministrationFactory': ['user'],
        'user.lexmarkUserFactory': ['user'],
        'user.roleFactory': ['user'],
        'user.directives': ['user'],
        'user.userAddController': ['user'],
        'user.lexmarkUserAddController': ['user'],
        'user.lexmarkUserListController': ['user'],
        'user.userController': ['user'],
        'user.usersController': ['user'],
        'user.userTabController': ['user'],
        'user.manageUserController': ['user'],
        'user.manageUserTabController': ['user'],
        'user.invitedUserController': ['user'],
        'user.impersonateUserListController': ['user'],

        'notification': ['angular'],
        'notification.notificationFactory': ['notification'],
        'notification.notificationController': ['notification'],
        'notification.directives': ['notification'],
        'notification.createNotificationController': ['notification'],
        'notification.manageNotificationController': ['notification'],

        'siebel': ['angular'],
        'siebel.siebelFactory': ['siebel'],
        'siebel.siebelListController': ['siebel'],
        'siebel.directives': ['siebel'],
        'siebel.createSiebelValueController': ['siebel'],
        'siebel.manageSiebelValueController': ['siebel'],

        'address': ['angular'],
        'address.addressAddController': ['address'],
        'address.addressUpdateController': ['address'],
        'address.addressDeleteController': ['address'],
        'address.addressController': ['address'],
        'address.addressListController': ['address'],
        'address.directives': ['address'],
        'address.factory': ['address'],

        'report': ['angular', 'angular-route'],
        'report.reportController': ['report', 'report.factory'],
        'report.reportListController': ['report', 'report.factory'],
        'report.reportFinderController': ['report', 'report.factory'],
        'report.directives': ['report'],
        'report.factory': ['report'],

        'angular-gatekeeper': ['angular-cookies', 'angular-route'],

        'ui.grid' : ['angular', 'pdfmake']
    },
    paths: {
        'lxk.fef': 'etc/lxk-framework/js/lxk-framework.min',

        'angular': 'app/libs/angular.min',
        'angular-resource': 'app/libs/angular-resource.min',
        'angular-route': 'app/libs/angular-route.min',
        'angular-cookies': 'app/libs/angular-cookies.min',
        'angular-translate': 'app/libs/angular-translate.min',
        'angular-translate-storage-cookie': 'app/libs/angular-translate-storage-cookie.min',
        'angular-translate-storage-local': 'app/libs/angular-translate-storage-local.min',
        'angular-translate-loader-static-files': 'app/libs/angular-translate-loader-static-files.min',
        'angular-translate-loader-url': 'app/libs/angular-translate-loader-url.min',
        'angular-spring-data-rest': 'app/libs/angular-spring-data-rest.min',

        'googlecharting': 'app/libs/ng-google-chart',
        'vButton': 'app/libs/v-button.min',

        'rome': 'app/libs/rome.min',

        'ngTagsInput': 'app/libs/ng-tags-input.min',

        'pdfmake': 'app/libs/vfs_fonts',
        'pdfMakeLib': 'app/libs/pdfmake.min',

        'angular-sanitize': 'app/libs/angular-sanitize.min',

        'ui.grid' : 'app/libs/ui-grid/3.0.6/ui-grid',

        'app': 'app/app',

        'attachments' : 'app/attachments/attachments',
        'attachments.directives' : 'app/attachments/directives',

        'hateoasFactory': 'app/hateoas_factory/hateoasFactory',
        'hateoasFactory.serviceFactory': 'app/hateoas_factory/hateoasServiceFactory',

        'filterSearch': 'app/filter_search/filterSearch',
        'filterSearch.gridFilterController': 'app/filter_search/gridFilterController',
        'filterSearch.accountFilterController': 'app/filter_search/accountFilterController',
        'filterSearch.gridSearchController': 'app/filter_search/gridSearchController',
        'filterSearch.chlFilterController': 'app/filter_search/chlFilterController',
        'filterSearch.locationFilterController': 'app/filter_search/locationFilterController',
        'filterSearch.bookmarkFilterController': 'app/filter_search/bookmarkFilterController',
        'filterSearch.statusFilterController': 'app/filter_search/statusFilterController',
        'filterSearch.orderStatusFilterController': 'app/filter_search/orderStatusFilterController',
        'filterSearch.requestStatusFilterController': 'app/filter_search/requestStatusFilterController',
        'filterSearch.supplyOrderTypeFilterController': 'app/filter_search/supplyOrderTypeFilterController',
        'filterSearch.deviceRequestTypeFilterController': 'app/filter_search/deviceRequestTypeFilterController',
        'filterSearch.invitedStatusFilterController': 'app/filter_search/invitedStatusFilterController',
        'filterSearch.roleFilterController': 'app/filter_search/roleFilterController',
        'filterSearch.dateRangeFilterController': 'app/filter_search/dateRangeFilterController',
        'filterSearch.invoiceDateFilterController': 'app/filter_search/invoiceDateFilterController',
        'filterSearch.soldToFilterController': 'app/filter_search/soldToFilterController',
        'filterSearch.libraryFilterController': 'app/filter_search/libraryFilterController',
        'filterSearch.meterReadTypeFilterController': 'app/filter_search/meterReadTypeFilterController',
        'filterSearch.filterSearchService': 'app/filter_search/filterSearchService',
        'filterSearch.directives': 'app/filter_search/directives',

        'security': 'app/security/security',
        'security.securityService': 'app/security/securityService',
        'security.securityHelper': 'app/security/securityHelper',

        'queue': 'app/queue/queue',
        'queue.directives': 'app/queue/directives',
        'queue.queueNotificationController': 'app/queue/queueNotificationController',
        'queue.queueListController': 'app/queue/queueListController',
        'queue.tombstoneFactory': 'app/queue/tombstoneFactory',

        'nav': 'app/nav/nav',
        'nav.navController': 'app/nav/navController',
        'nav.navFactory': 'app/nav/navFactory',
        'nav.navItemFactory': 'app/nav/navItemFactory',
        'nav.directives': 'app/nav/directives',

        'form': 'app/form/form',
        'form.datePicker': 'app/form/datePickerController',
        'form.directives': 'app/form/directives',

        'utility': 'app/utilities/utility',
        'utility.historyUtility': 'app/utilities/historyUtility',
        'utility.blankCheckUtility': 'app/utilities/blankCheckUtility',
        'utility.directives': 'app/utilities/directives',
        'utility.controller': 'app/utilities/controller',
        'utility.contactPickerController': 'app/utilities/contactPickerController',
        'utility.addressPickerController': 'app/utilities/addressPickerController',
        'utility.addressBillToPickerController': 'app/utilities/addressBillToPickerController',
        'utility.addressShipToPickerController': 'app/utilities/addressShipToPickerController',
        'utility.devicePickerController': 'app/utilities/devicePickerController',
        'utility.pageCountSelectController': 'app/utilities/pageCountSelectController',
        'utility.pageCountSelectService': 'app/utilities/pageCountSelectService',
        'utility.personalizationService': 'app/utilities/personalizationService',
        'utility.urlHelper': 'app/utilities/urlHelper',
        'utility.recursionHelper': 'app/utilities/recursionHelper',
        'utility.formatters': 'app/utilities/formatters',
        'utility.hateaosConfig': 'app/utilities/hateaosConfig',
        'utility.hateaosFactory': 'app/utilities/hateaosFactory',
        'utility.grid': 'app/utilities/grid',
        'utility.imageService': 'app/utilities/imageService',
        'utility.columnPickerController': 'app/utilities/columnPickerController',
        'utility.accountPickerController': 'app/utilities/accountPickerController',
        'utility.printExportTitleController': 'app/utilities/printExportTitleController',

        'account': 'app/accounts/account',
        'account.accountFactory': 'app/accounts/accountFactory',
        'account.roleFactory': 'app/accounts/roleFactory',
        'account.accountController': 'app/accounts/accountController',

        'notification': 'app/notifications/notification',
        'notification.notificationFactory': 'app/notifications/notificationFactory',
        'notification.notificationController': 'app/notifications/notificationListController',
        'notification.directives': 'app/notifications/directives',
        'notification.createNotificationController': 'app/notifications/createNotificationController',
        'notification.manageNotificationController': 'app/notifications/manageNotificationController',

        'siebel': 'app/siebel/siebel',
        'siebel.siebelFactory': 'app/siebel/siebelFactory',
        'siebel.siebelListController': 'app/siebel/siebelListController',
        'siebel.directives': 'app/siebel/directives',
        'siebel.createSiebelValueController': 'app/siebel/createSiebelValueController',
        'siebel.manageSiebelValueController': 'app/siebel/manageSiebelValueController',

        'user': 'app/users/user',
        'user.factory': 'app/users/usersFactory',
        'user.userInfoFactory': 'app/users/userInfoFactory',
        'user.allAccountFactory': 'app/users/allAccountFactory',
        'user.userAdministrationFactory': 'app/users/userAdministrationFactory',
        'user.lexmarkUserFactory': 'app/users/lexmarkUserFactory',
        'user.roleFactory': 'app/users/roleFactory',
        'user.impersonateFactory': 'app/users/impersonateFactory',
        'user.directives': 'app/users/directives',
        'user.userAddController': 'app/users/userAddController',
        'user.lexmarkUserListController': 'app/users/lexmarkUserListController',
        'user.lexmarkUserAddController': 'app/users/lexmarkUserAddController',
        'user.userController': 'app/users/userController',
        'user.usersController': 'app/users/usersController',
        'user.userTabController': 'app/users/userTabController',
        'user.manageUserTabController': 'app/users/manageUserTabController',
        'user.manageUserController': 'app/users/manageUserController',
        'user.invitedUserController': 'app/users/invitedUserController',
        'user.impersonateUserListController': 'app/users/impersonateUserListController',

        'serviceRequest': 'app/service_requests/serviceRequest',
        'serviceRequest.factory': 'app/service_requests/serviceRequestsFactory',
        'serviceRequest.serviceRequestStatusFactory': 'app/service_requests/serviceRequestStatusFactory',
        'serviceRequest.serviceRequestTypeFactory': 'app/service_requests/serviceRequestTypeFactory',
        'serviceRequest.directives': 'app/service_requests/directives',
        'serviceRequest.detailController': 'app/service_requests/serviceRequestDetailController',
        'serviceRequest.cancelController': 'app/service_requests/serviceRequestCancelController',
        'serviceRequest.updateController': 'app/service_requests/serviceRequestUpdateController',
        'serviceRequest.openServiceRequestController': 'app/service_requests/openServiceRequestController',
        'serviceRequest.listController': 'app/service_requests/serviceRequestListController',
        'serviceRequest.listDeviceController': 'app/service_requests/serviceRequestDeviceListController',
        'serviceRequest.listBreakFixController': 'app/service_requests/serviceRequestBreakFixListController',
        'serviceRequest.listAddressController': 'app/service_requests/serviceRequestAddressListController',
        'serviceRequest.listContactController': 'app/service_requests/serviceRequestContactListController',
        'serviceRequest.TabController': 'app/service_requests/serviceRequestTabController',
        'serviceRequest.ActionButtonController': 'app/service_requests/serviceRequestActionButtonsController',
        'serviceRequest.controllerHelperService': 'app/service_requests/srControllerHelperService',

        'order': 'app/orders/order',
        'order.factory': 'app/orders/ordersFactory',
        'order.orderTypeFactory': 'app/orders/orderTypeFactory',
        'order.orderStatusFactory': 'app/orders/orderStatusFactory',
        'order.orderItemsfactory': 'app/orders/orderItemsFactory',
        'order.assetsPartsFactory': 'app/orders/assetPartsFactory',
        'order.hardwareCatalogFactory': 'app/orders/hardwareCatalogFactory',
        'order.suppliesCatalogFactory': 'app/orders/suppliesCatalogFactory',
        'order.directives': 'app/orders/directives',
        'order.catalogController':'app/orders/catalogController',
        'order.orderPurchaseController': 'app/orders/orderPurchaseController',
        'order.orderCatalogPurchaseController': 'app/orders/orderCatalogPurchaseController',
        'order.orderListController': 'app/orders/orderListController',
        'order.deviceOrderListController': 'app/orders/deviceOrderListController',
        'order.supplyOrderListController': 'app/orders/supplyOrderListController',
        'order.orderSupplyController': 'app/orders/orderSupplyController',
        'order.orderContentsController': 'app/orders/orderContentsController',
        'order.tabController': 'app/orders/orderTabController',
        'order.actionButtonController': 'app/orders/orderActionButtonsController',
        'order.returnOrdersController': 'app/orders/returnOrdersController',
        'order.agreementCatalogController': 'app/orders/agreementCatalogController',
        'order.agreementFactory':'app/orders/agreementFactory',
        'order.contractFactory':'app/orders/contractFactory',

        'address': 'app/address_service_requests/addressServiceRequest',
        'address.addressAddController': 'app/address_service_requests/addressAddController',
        'address.addressUpdateController': 'app/address_service_requests/addressUpdateController',
        'address.addressDeleteController': 'app/address_service_requests/addressDeleteController',
        'address.addressController': 'app/address_service_requests/addressController',
        'address.addressListController': 'app/address_service_requests/addressListController',
        'address.directives': 'app/address_service_requests/directives',
        'address.factory': 'app/address_service_requests/addressesFactory',

        'contact': 'app/contact_service_requests/contactServiceRequest',
        'contact.contactController': 'app/contact_service_requests/contactController',
        'contact.contactDeleteController': 'app/contact_service_requests/contactDeleteController',
        'contact.contactListController': 'app/contact_service_requests/contactListController',
        'contact.contactAddController': 'app/contact_service_requests/contactAddController',
        'contact.contactUpdateController': 'app/contact_service_requests/contactUpdateController',
        'contact.contactUpdateTabController': 'app/contact_service_requests/contactUpdateTabController',
        'contact.contactUpdateAddressController': 'app/contact_service_requests/contactUpdateAddressController',
        'contact.directives': 'app/contact_service_requests/directives',
        'contact.factory': 'app/contact_service_requests/contactsFactory',

        'invoice': 'app/invoices/invoice',
        'invoice.invoiceController': 'app/invoices/invoiceController',
        'invoice.directives': 'app/invoices/directives',
        'invoice.invoiceListController': 'app/invoices/invoiceListController',
        'invoice.invoiceListFactory': 'app/invoices/invoiceListFactory',

        'pageCount': 'app/page_count/pageCount',
        'pageCount.directives': 'app/page_count/directives',
        'pageCount.missingPageCountListController': 'app/page_count/missingPageCountListController',
        'pageCount.pageCountTabController': 'app/page_count/pageCountTabController',
        'pageCount.pageCountListController': 'app/page_count/pageCountListController',
        'pageCount.pageCountFactory': 'app/page_count/pageCountFactory',

        'deviceManagement': 'app/device_management/deviceManagement',
        'deviceManagement.deviceController': 'app/device_management/deviceController',
        'deviceManagement.deviceListController': 'app/device_management/deviceListController',
        'deviceManagement.deviceInformationController': 'app/device_management/deviceInformationController',
        'deviceManagement.deviceOrderController': 'app/device_management/deviceOrderController',
        'deviceManagement.deviceRequestBreakFixController': 'app/device_management/deviceRequestBreakFixListController',
        'deviceManagement.directives': 'app/device_management/directives',
        'deviceManagement.deviceFactory': 'app/device_management/deviceFactory',
        'deviceManagement.deviceLocationFactory': 'app/device_management/deviceLocationFactory',
        'deviceManagement.productModelFactory': 'app/device_management/productModelFactory',
        'deviceManagement.meterReadFactory': 'app/device_management/meterReadFactory',
        'deviceManagement.deviceRequestFactory': 'app/device_management/deviceRequestFactory',
        'deviceManagement.deviceNotificationController': 'app/device_management/deviceNotificationController',

        'deviceServiceRequest': 'app/device_service_requests/deviceServiceRequest',
        'deviceServiceRequest.deviceAddController': 'app/device_service_requests/deviceAddController',
        'deviceServiceRequest.deviceUpdateController': 'app/device_service_requests/deviceUpdateController',
        'deviceServiceRequest.deviceSearchController': 'app/device_service_requests/deviceSearchController',
        'deviceServiceRequest.deviceServiceRequestDeviceController': 'app/device_service_requests/deviceServiceRequestDeviceController',
        'deviceServiceRequest.deviceDecommissionController': 'app/device_service_requests/deviceDecommissionController',
        'deviceServiceRequest.directives': 'app/device_service_requests/directives',
        'deviceServiceRequest.deviceSearchFactory': 'app/device_service_requests/deviceSearchFactory',
        'deviceServiceRequest.deviceServiceRequestFactory': 'app/device_service_requests/deviceServiceRequestFactory',

        'library': 'app/library/library',
        'library.libraryListController': 'app/library/libraryListController',
        'library.libraryController': 'app/library/libraryController',
        'library.libraryDeleteInlineController': 'app/library/libraryDeleteInlineController',
        'library.libraryViewController': 'app/library/libraryViewController',
        'library.libraryTagController': 'app/library/libraryTagController',
        'library.libraryFactory': 'app/library/libraryFactory',
        'library.libraryTagFactory': 'app/library/libraryTagFactory',
        'library.libraryOwnerFactory': 'app/library/libraryOwnerFactory',
        'library.directives': 'app/library/directives',

        'report': 'app/reporting/report',
        'report.reportController': 'app/reporting/reportController',
        'report.reportListController': 'app/reporting/reportListController',
        'report.reportFinderController': 'app/reporting/reportFinderController',
        'report.directives': 'app/reporting/directives',
        'report.factory': 'app/reporting/reportFactory',

        'dashboard': 'app/dashboard/dashboard',
        'dashboard.dashboardController': 'app/dashboard/dashboardController',

        'angular-gatekeeper': 'app/libs/angular-gatekeeper',

        'tree': 'app/tree/module',
        'tree.treeItemsService': 'app/tree/treeItemsService',
        'tree.treeController': 'app/tree/treeController',
        'tree.treeItemController': 'app/tree/treeItemController',
        'tree.directives': 'app/tree/directives'
    },
    map: {
        '*': {
            'jquery': 'jquery-private',
            'stable': 'modules'
        },
        'jquery-private': {'jquery': 'jquery'}
    },
    bundles: {
        'lxk.fef': [
            'jquery',
            'fef.jquery',
            'jquery-private',
            'throttle-debounce',
            'modernizr',
            'variables',
            'modules/alerts',
            'modules/banner',
            'modules/breadcrumb',
            'modules/card',
            'modules/carousel',
            'modules/custom-input',
            'modules/dropdown',
            'modules/form-selectbox',
            'modules/form',
            'modules/griddy',
            'modules/media-queries',
            'modules/modal',
            'modules/modalmanager',
            'modules/quote',
            'modules/rail-nav',
            'modules/responsive-images',
            'modules/responsive-tables',
            'modules/set',
            'modules/sifter',
            'modules/slide-in-panel'
        ]
    }
});
