

angular.module('mps.report')
.factory('Reports', ['$translate', 'HATEOASFactory',
    function($translate, HATEOASFactory) {
        var Report = {
            serviceName: 'reports',
            embeddedName: 'reportTypes',
            columns: 'defaultSet',
            columnDefs: {
                defaultSet: [
                    {'name': $translate.instant('REPORTING.NAME'), 'field': 'name',
                     'cellTemplate':'<div>' +
                                        '<a href="#" ng-click="grid.appScope.goToFinder(row.entity);">{{row.entity.name}}</a>' +
                                    '</div>'
                    }
                ],
                /* Asset Register */
                mp9058sp: [
                    {'name': $translate.instant('REPORTING.REPORTING_HIERARCHY'), 'field': 'chl', minWidth: 420},
                    {'name': $translate.instant('REPORTING.ADDRESS_NAME'), 'field': 'addressName', minWidth: 240},
                    {'name': $translate.instant('REPORTING.DEVICE'), 'field': 'device', minWidth: 120},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_TAG'), 'field': 'assetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE_TAG_CUSTOMER'), 'field': 'deviceTagCustomer', minWidth: 240},
                    {'name': $translate.instant('REPORTING.DEVICE_STATUS'), 'field': 'deviceStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LAST_LTPC'), 'field': 'lastLtpc', minWidth: 120},
                    {'name': $translate.instant('REPORTING.LAST_LTPC_DATE'), 'field': 'lastLtpcDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150 },
                    {'name': $translate.instant('REPORTING.IP_ADDRESS'), 'field': 'ipAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.HOST_NAME'), 'field': 'hostName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MAC_ADDRESS'), 'field': 'macAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DIVISION'), 'field': 'division', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LIFE_CYCLE'), 'field': 'lifeCycle', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STORE_FRONT_NAME'), 'field': 'storeFrontName', minWidth: 210},
                    {'name': $translate.instant('REPORTING.COST_CENTER'), 'field': 'costCenter', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEPT_NUMBER'), 'field': 'departNumber', minWidth: 180},
                    {'name': $translate.instant('REPORTING.DEPT_NAME'), 'field': 'departmentName', minWidth: 180},
                    {'name': $translate.instant('REPORTING.INSTALL_DATE'), 'field': 'installDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TERM_START_DATE'), 'field': 'termStartDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TERM_END_DATE'), 'field': 'termEndDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TERMS'), 'field': 'terms', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ADDRESS'), 'field': 'address', minWidth: 240},
                    {'name': $translate.instant('REPORTING.CITY'), 'field': 'city', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'state', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PROVINCE'), 'field': 'province', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ZIPCODE'), 'field': 'zipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTY'), 'field': 'county', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_1'), 'field': 'phyLoc1', minWidth: 240},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_2'), 'field': 'phyLoc2', minWidth: 240},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_3'), 'field': 'phyLoc3', minWidth: 240},
                    {'name': $translate.instant('REPORTING.AGREEMENT'), 'field': 'agreement', minWidth: 150}
                ],
                /* MADC */
                mp9073: [
                    {'name': $translate.instant('REPORTING.ACCOUNT_NAME'), 'field': 'accountName', minWidth: 270},
                    {'name': $translate.instant('REPORTING.ASSET_TAG'), 'field': 'assetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE'), 'field': 'device', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EVENT_DATE'), 'field': 'eventDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EVENT_TYPE'), 'field': 'type', minWidth: 150},
                    {'name': $translate.instant('REPORTING.GEO'), 'field': 'geo', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MANUFACTURER'), 'field': 'manufacturer', minWidth: 150},
                    {'name': $translate.instant('REPORTING.NEW_ADDRESS_NAME'), 'field': 'newAddress', minWidth: 240},
                    {'name': $translate.instant('REPORTING.NEW_ASSET_SERIAL_NUMBER'), 'field': 'newSerialNumber', minWidth: 240},
                    {'name': $translate.instant('REPORTING.NEW_IP_ADDRESS'), 'field': 'newIp', minWidth: 150},
                    {'name': $translate.instant('REPORTING.NEW_REPORTING_HIERARCHY'), 'field': 'newChl', minWidth: 240},
                    {'name': $translate.instant('REPORTING.OLD_ADDRESS_NAME'), 'field': 'oldAddress', minWidth: 240},
                    {'name': $translate.instant('REPORTING.OLD_IP_ADDRESS'), 'field': 'oldIp', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OLD_REPORTING_HIERARCHY'), 'field': 'oldChl', minWidth: 240},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field':'origSerialNumber', minWidth: 150}
                ],
                /* Missing Meter Reads */
                mp0075: [
                    {'name': $translate.instant('REPORTING.REPORTING_HIERARCHY'), 'field': 'reportHierarchy', minWidth: 420},
                    {'name': $translate.instant('REPORTING.ADDRESS_NAME'), 'field': 'addressName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MANUFACTURER'), 'field': 'manufacturer', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE'), 'field': 'device', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_TAG'), 'field': 'assetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CUSTOMER_ASSET_TAG'), 'field': 'customerAssetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MEASUREMENT'), 'field': 'measurement', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LASTEST_READ'), 'field': 'lastestRead', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LASTEST_READ_DATE'), 'field': 'lastestReadDate', minWidth: 180},
                    {'name': $translate.instant('REPORTING.IP_ADDRESS'), 'field': 'ipAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ADDRESS_LINE_1'), 'field': 'addressLn1', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CITY'), 'field': 'city', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'state', minWidth: 150},
                    {'name': $translate.instant('REPORTING.POSTAL_CODE'), 'field': 'zipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COST_CENTER'), 'field': 'costCentre', minWidth: 150},
                    {'name': $translate.instant('REPORTING.BUILDING_NAME'), 'field': 'buildingName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.FLOOR_NAME'), 'field': 'floorName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OFFICE_NAME'), 'field': 'officeName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ZONE_NAME'), 'field': 'zoneName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SITE_NAME'), 'field': 'siteName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.HOST_NAME'), 'field': 'hostName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.AGREEMENT'), 'field': 'agreement', minWidth: 150},
                    {'name': $translate.instant('REPORTING.METER_SOURCE'), 'field': 'meterSource', minWidth: 150}
                ],
                /* Consumables Orders */
                mp0021: [
                    {'name': $translate.instant('REPORTING.SR_SOURCE'), 'field': 'srSource', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACCOUNT_NAME'), 'field': 'accountName', minWidth: 240},
                    {'name': $translate.instant('REPORTING.ACCOUNT_SITE'), 'field': 'accountSite', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACCOUNT_ORGANIZATION'), 'field': 'accountOrg', minWidth: 210},
                    {'name': $translate.instant('REPORTING.AGREEMENT_NAME'), 'field': 'agreementName', minWidth: 330},
                    {'name': $translate.instant('REPORTING.AGREEMENT_NUMBER'), 'field': 'agreementNumber', minWidth: 180},
                    {'name': $translate.instant('REPORTING.SR_NUMBER'), 'field': 'srNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ORDER_NUMBER'), 'field': 'orderNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_DATE'), 'field': 'orderDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_STATUS'), 'field': 'orderStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_TYPE'), 'field': 'orderType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CREATED_BY'), 'field': 'createdBy', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LINE_TYPE'), 'field': 'lineType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LINE_NUMBER'), 'field': 'lineNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LINE_STATUS'), 'field': 'lineStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_STATUS_DATE'), 'field': 'orderStatusDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SHIPPED_DATE'), 'field': 'shippedDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DELIVERED_DATE'), 'field': 'deliveredDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EXPEDITE_FLAG'), 'field': 'expediteFlag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COST_CENTER'), 'field': 'costCenter', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PO_NUMBER'), 'field': 'poNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SUPPLY_TYPE'), 'field': 'supplyType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MATERIAL'), 'field': 'material', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MATERIAL_DESCRIPTION'), 'field': 'materialDescription', minWidth: 240},
                    {'name': $translate.instant('REPORTING.ADDRESS_LINE_1'), 'field': 'addressLine1', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ADDRESS_LINE_2'), 'field': 'addressLine2', minWidth: 210},
                    {'name': $translate.instant('REPORTING.CITY'), 'field': 'city', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'state', minWidth: 150},
                    {'name': $translate.instant('REPORTING.POSTAL_CODE'), 'field': 'zipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PROVINCE'), 'field': 'province', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CUSTOMER_CONTACT_NAME'), 'field': 'customerContactName', minWidth: 210},
                    {'name': $translate.instant('REPORTING.PHONE_NUMBER'), 'field': 'phoneNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EMAIL_ADDRESS'), 'field': 'emailAddress', minWidth: 210},
                    {'name': $translate.instant('REPORTING.QUANTITY'), 'field': 'quantity', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CARRIER'), 'field': 'carrier', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TRACKING_NUMBER'), 'field': 'trackingNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ASSET_TAG'), 'field': 'assetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IP_ADDRESS'), 'field': 'ipAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SUPPLIER_NAME'), 'field': 'supplierName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.UNIT_PRICE'), 'field': 'unitPrice', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_PRICE'), 'field': 'orderPrice', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CUSTOMER_REFERENCE_NUMBER'), 'field': 'customerRefNumber', minWidth: 240},
                    {'name': $translate.instant('REPORTING.INSIDE_LOCATION'), 'field': 'insideLocation', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PRINTER_MATERIAL_NUMBER'), 'field': 'printerMaterialNum', minWidth: 210},
                    {'name': $translate.instant('REPORTING.FAMILY'), 'field': 'family', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MODEL_NUMBER'), 'field': 'model', minWidth: 150},
                    {'name': $translate.instant('REPORTING.HOST_NAME'), 'field': 'hostName', minWidth: 150}
                ],
                /* Hardware Orders */
                hw0008: [
                    {'name': $translate.instant('REPORTING.ACCOUNT'), 'field': 'account', minWidth: 240},
                    {'name': $translate.instant('REPORTING.AREA'), 'field': 'srArea', minWidth: 150},
                    {'name': $translate.instant('REPORTING.BILLING_MODEL'), 'field': 'billingModel', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CARRIER'), 'field': 'carrier', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COMMENTS'), 'field': 'comments', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CUSTOMER_PO_NUMBER'), 'field': 'customerPo', minWidth: 210},
                    {'name': $translate.instant('REPORTING.CUSTOMER_REQUESTED_DATE'), 'field': 'customerRequestedDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 210},
                    {'name': $translate.instant('REPORTING.DELIVERED_DATE'), 'field': 'deliveredDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DELIVERY_CONTACT_EMAIL_ADDRESS'), 'field': 'deliveryContactEmail', minWidth: 270},
                    {'name': $translate.instant('REPORTING.DELIVERY_CONTACT_NAME'), 'field': 'deliveryContactName', minWidth: 210},
                    {'name': $translate.instant('REPORTING.DELIVERY_CONTACT_PHONE_NUMBER'), 'field': 'deliveryContactPhoneNumber', minWidth: 270},
                    {'name': $translate.instant('REPORTING.DELIVERY_INSTRUCTIONS'), 'field': 'deliveryInstructions', minWidth: 210},
                    {'name': $translate.instant('REPORTING.EAI_SYNC_STATUS'), 'field': 'eaiSyncStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EXPEDITE'), 'field': 'expedite', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EXTERNAL_ORDER_NUMBER'), 'field': 'externalOrderNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.FREIGHT_FORWARDER_NUMBER'), 'field': 'freightForwaderNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.FULFILLED_QUANTITY'), 'field': 'fullfillQty', minWidth: 210},
                    {'name': $translate.instant('REPORTING.FULFILLMENT_TYPE'), 'field': 'fufillmentType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.HELP_DESK_REFERENCE_NUMBER'), 'field': 'helpDeskRefNumber', minWidth: 240},
                    {'name': $translate.instant('REPORTING.HARDWARE_CONFIG_ID'), 'field': 'hwConfigId', minWidth: 180},
                    {'name': $translate.instant('REPORTING.INVENTORY_PARTNER_ADDRESS'), 'field': 'inventoryPartnerAddress', minWidth: 210},
                    {'name': $translate.instant('REPORTING.INVENTORY_PARTNER_FLAG'), 'field': 'inventoryPartnerFlag', minWidth: 210},
                    {'name': $translate.instant('REPORTING.INVENTORY_PARTNER_SHIP_TO'), 'field': 'inventoryPartnerShipTo', minWidth: 210},
                    {'name': $translate.instant('REPORTING.LINE_NUMBER'), 'field': 'lineNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.LINE_TYPE'), 'field': 'lineType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MODEL'), 'field': 'model', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_DATE'), 'field': 'orderDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_HEADER_STATUS'), 'field': 'orderHeaderStatus', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_STATUS'), 'field': 'lineStatus', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ORDER_NUMBER'), 'field': 'orderNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_TYPE'), 'field': 'orderType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDERED_AS'), 'field': 'orderedAs', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDERED_PRODUCT'), 'field': 'orderedProduct', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PARENT_CONFIG_ID'), 'field': 'parentConfigId', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PAYMENT_METHOD'), 'field': 'paymentMethod', minWidth: 210},
                    {'name': $translate.instant('REPORTING.PRODUCT'), 'field': 'product', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PRODUCT_DESCRIPTION'), 'field': 'productDescription', minWidth: 210},
                    {'name': $translate.instant('REPORTING.PROJECT'), 'field': 'project', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PROJECT_PHASE'), 'field': 'projectPhase', minWidth: 150},
                    {'name': $translate.instant('REPORTING.QUANTITY_REQUESTED'), 'field': 'qtyRequested', minWidth: 210},
                    {'name': $translate.instant('REPORTING.REQUESTED_SHIP_DATE'), 'field': 'requestedShipDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SAP_CONTRACT_NUMBER'), 'field': 'sapContractNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERVICE_ADDRESS'), 'field': 'serviceAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SHIPMENT_METHOD'), 'field': 'shipmentMethod', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SHIPPED_DATE'), 'field': 'shippedDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SHIPPING_METHOD'), 'field': 'shippingMethod', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SOLD_TO_NUMBER'), 'field': 'soldToNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SOLUTION_LINE_NUMBER'), 'field': 'solutionLineNumber', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SOURCE_LOCATION'), 'field': 'sourceLocation', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_CONTACT_EMAIL_ADDRESS'), 'field': 'srContactEmail', minWidth: 240},
                    {'name': $translate.instant('REPORTING.SR_CONTACT_NAME'), 'field': 'srContactName', minWidth: 210},
                    {'name': $translate.instant('REPORTING.SR_CONTACT_WORK_PHONE_NUMBER'), 'field': 'srContactPhoneNumber', minWidth: 270},
                    {'name': $translate.instant('REPORTING.SR_NUMBER'), 'field': 'srNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_TYPE'), 'field': 'srType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SUB_AREA'), 'field': 'srSubArea', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TRACKING_NUMBER'), 'field': 'trackingNumber', minWidth: 180},
                    {'name': $translate.instant('REPORTING.WHITE_GLOVE'), 'field': 'whiteGlove', minWidth: 150}
                ],
                /* Pages Billed */
                pb0001: [
                    {'name': $translate.instant('REPORTING.ACCOUNT'), 'field': 'account', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CHL'), 'field': 'chl', minWidth: 150},
                    {'name': $translate.instant('REPORTING.GEO'), 'field': 'geo', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MODEL'), 'field': 'model', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_1'), 'field': 'phyLoc1', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_2'), 'field': 'phyLoc2', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PHYSICAL_LOC_3'), 'field': 'phyLoc3', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE'), 'field': 'device', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE_DESCRIPTION'), 'field': 'deviceDesc', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_NUMBER'), 'field': 'assetNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_ADDRESS_LINE_1'), 'field': 'installAddressLn1', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_ADDRESS_LINE_2'), 'field': 'installAddressLn2', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_CITY'), 'field': 'installCity', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'installState', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ZIPCODE'), 'field': 'installZipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_DATE'), 'field': 'installDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MANUFACTURER'), 'field': 'manufacturer', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_IP'), 'field': 'assetIp', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_TAG'), 'field': 'assetTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.AGREEMENT'), 'field': 'agreement', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PAGES_BILLED_MONO'), 'field': 'pagesBilledMono', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PAGES_BILLED_COLOR'), 'field': 'pagesBilledColor', minWidth: 150}
                ],
                /* Hardware Installation Requests */
                hw0015: [
                    {'name': $translate.instant('REPORTING.ACTIVITY_NUMBER'), 'field': 'activityNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACTIVITY_CREATED_DATE'), 'field': 'activityCreatedDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 210},
                    {'name': $translate.instant('REPORTING.ACTIVITY_TYPE'), 'field': 'activityType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACTIVITY_STATUS'), 'field': 'activityStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACTIVITY_SUB_STATUS'), 'field': 'activitySubStatus', minWidth: 180},
                    {'name': $translate.instant('REPORTING.COMMENTS'), 'field': 'comments', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_NUMBER'), 'field': 'srNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_SUB_AREA'), 'field': 'srSubArea', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EXPECTED_START_DATE'), 'field': 'expectedStartDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 180},
                    {'name': $translate.instant('REPORTING.EXPECTED_END_DATE'), 'field': 'expectedEndDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 180},
                    {'name': $translate.instant('REPORTING.PROJECT'), 'field': 'project', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEBRIEF_STATUS'), 'field': 'debriefStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_ADDRESS_LINE_1'), 'field': 'installAddressLn1', minWidth: 180},
                    {'name': $translate.instant('REPORTING.INSTALL_ADDRESS_LINE_2'), 'field': 'installAddressLn2', minWidth: 150},
                    {'name': $translate.instant('REPORTING.INSTALL_CITY'), 'field': 'installCity', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'state', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PROVINCE'), 'field': 'province', minWidth: 150},
                    {'name': $translate.instant('REPORTING.POSTAL_CODE'), 'field': 'zipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PRODUCT'), 'field': 'product', minWidth: 150},
                    {'name': $translate.instant('REPORTING.PRODUCT_NAME'), 'field': 'productName', minWidth: 240},
                    {'name': $translate.instant('REPORTING.PRODUCT_GROUP'), 'field': 'productGroup', minWidth: 150},
                    {'name': $translate.instant('REPORTING.QUANTITY'), 'field': 'quantity', minWidth: 150},
                    {'name': $translate.instant('REPORTING.USED_QUANTITY'), 'field': 'usedQty', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DOA_QUANTITY'), 'field': 'doaQty', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_PHYSICAL_LOC_1'), 'field': 'obPhysicalLoc1', minWidth: 210},
                    {'name': $translate.instant('REPORTING.OB_PHYSICAL_LOC_2'), 'field': 'obPhysicalLoc2', minWidth: 210},
                    {'name': $translate.instant('REPORTING.OB_PHYSICAL_LOC_3'), 'field': 'obPhysicalLoc3', minWidth: 210},
                    {'name': $translate.instant('REPORTING.OB_IP_ADDRESS'), 'field': 'obIpAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_MAC_ADDRESS'), 'field': 'obMacAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_HOST_NAME'), 'field': 'obHostName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_SERIAL_NUMBER'), 'field': 'obSerialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_INSTALL_DATE'), 'field': 'obInstallDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_PROJECT'), 'field': 'obProject', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_PHYSICAL_LOC_1'), 'field': 'ibPhysicalLoc1', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_PHYSICAL_LOC_2'), 'field': 'ibPhysicalLoc2', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_PHYSICAL_LOC_3'), 'field': 'ibPhysicalLoc3', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_IP_ADDRESS'), 'field': 'ibIpAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_MAC_ADDRESS'), 'field': 'ibMacAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_HOST_NAME'), 'field': 'ibHostName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_SERIAL_NUMBER'), 'field': 'ibSerialNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_INSTALL_DATE'), 'field': 'ibInstallDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CONTACT2_LASTNAME'), 'field': 'contactLastName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CONTACT2_FIRSTNAME'), 'field': 'contactFirstName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_DEINSTALL_BRAND'), 'field': 'obDeInstallBrand', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_DEINSTALL_IP_ADDRESS'), 'field': 'obDeInstallIpAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_DEINSTALL_MODEL'), 'field': 'obDeInstallModel', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_DEINSTALL_REMOVAL_DATE'), 'field': 'obDeInstallRemovalDate', 'cellFilter': 'date:\'yyyy-MM-dd\'', minWidth: 150},
                    {'name': $translate.instant('REPORTING.OB_DEINSTALL_SERIAL_NUMBER'), 'field': 'obDeInstallSerialNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_DEINSTALL_SERIAL_NUMBER'), 'field': 'ibDeInstallSerialNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_DEINSTALL_BRAND'), 'field': 'ibDeInstallBrand', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_DEINSTALL_PRODUCT_NUMBER'), 'field': 'ibDeInstallPartNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_DEINSTALL_MODEL'), 'field': 'ibDeInstallModel', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IB_DEINSTALL_REMOVAL_DATE'), 'field': 'ibDeInstallModel', minWidth: 150}
                ],
                /* Service Detail Report */
                sd0101: [
                    {'name': $translate.instant('REPORTING.GEO'), 'field': 'geo', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COUNTRY'), 'field': 'country', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERVICE_PARTNER'), 'field': 'servicePartner', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_REFERENCE_NUMBER'), 'field': 'spReferenceNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TECHNICIAN_NAME'), 'field': 'technicianName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_NUMBER'), 'field': 'srNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_NUMBER'), 'field': 'orderNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.EXTERNAL_ORDER_NUMBER'), 'field': 'externalOrderNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.MACHINE_TYPE_MODEL'), 'field': 'machineTypeModel', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SR_CREATE_DATE'), 'field': 'srCreateDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CUSTOMER_ACCOUNT_NAME'), 'field': 'customerAccountName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.HELP_DESK_REFERENCE_NUMBER'), 'field': 'helpDeskRefNum', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ADDRESS_NAME'), 'field': 'addressName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERVICE_SUMMARY'), 'field': 'serviceSummary', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERIAL_NUMBER'), 'field': 'serialNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.IP_ADDRESS'), 'field': 'ipAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CITY'), 'field': 'city', minWidth: 150},
                    {'name': $translate.instant('REPORTING.STATE'), 'field': 'state', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ZIPCODE'), 'field': 'zipcode', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TECH_DEBRIEF'), 'field': 'techDebrief', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACTUAL_START'), 'field': 'actualStart', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ACTUAL_END'), 'field': 'actualEnd', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CONTACT2_LASTNAME'), 'field': 'contactLastName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CONTACT2_FIRSTNAME'), 'field': 'contactFirstName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CONTACT2_PHONE_NUMBER'), 'field': 'contactPhoneNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_TAG_CUSTOMER'), 'field': 'assetTagCustomer', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ASSET_TAG_LEXMARK'), 'field': 'assetTagLexmark', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CPN_SHORT_NAME'), 'field': 'cpnShortName', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SERVICE_TYPE'), 'field': 'serviceType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.COST_CENTER'), 'field': 'costCenter', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE_TAG_SERVICE_PARTNER'), 'field': 'deviceTagServicePartner', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DEVICE_TAG_SERVICE_TAG'), 'field': 'deviceTagServiceTag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.READY_FOR_SERVICE'), 'field': 'readyForServiceFlag', minWidth: 150},
                    {'name': $translate.instant('REPORTING.CHL'), 'field': 'chl', minWidth: 150},

                    {'name': $translate.instant('REPORTING.ORDER_TYPE'), 'field': 'orderType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_TYPE'), 'field': 'orderLineType', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_PN'), 'field': 'orderLinePn', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_PRODUCT_DESCRIPTION'), 'field': 'orderLineProdDesc', minWidth: 150},
                    {'name': $translate.instant('REPORTING.QUANTITY'), 'field': 'quantity', minWidth: 150},
                    {'name': $translate.instant('REPORTING.TRACKING_NUMBER'), 'field': 'trackingNumber', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_STATUS'), 'field': 'orderStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_STATUS'), 'field': 'orderLineStatus', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SHIP_TO_ADDRESS'), 'field': 'shipToAddress', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_CREATED_DATE'), 'field': 'orderCreatedDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_LINE_ITEM_CREATED'), 'field': 'orderLineItemCreated', minWidth: 150},
                    {'name': $translate.instant('REPORTING.SHIPPED_DATE'), 'field': 'shippedDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.RECEIVED_DATE'), 'field': 'receivedDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.DELIVERED_DATE'), 'field': 'deliveredDate', minWidth: 150},
                    {'name': $translate.instant('REPORTING.ORDER_STATUS_DATE'), 'field': 'orderStatusDate', minWidth: 150}
                ]
            },
            route: '/reporting',
            finder: {
                dateFrom: '',
                dateTo: '',
                selectType: '',
                    eventTypes: [
                        {value: 'Installs'},
                        {value: 'Moves'},
                        {value: 'IP Change'},
                        {value: 'Remove - Account'},
                        {value: 'Removes'},
                        {value: 'Manual Swaps'},
                        {value: 'Service Swaps'}
                    ],
                orderTypes: [{value: 'Consumable Supplies'}, {value: 'Consumable SVC Parts'}, {value: 'Consumable SVC Parts & Install'}],
                mmrDays: '60',
                mmrTypes: [{value: 'Manual'}, {value: 'Automated Electronic'}],
                srStatus: '',
                srStatusTypes: [{value: 'Open'}, {value: 'Close'}],
                withParts: '',
                withPartsTypes: [{value: 'yes'}, {value: 'no'}]
            }
        };

        return new HATEOASFactory(Report);
    }
]);

