# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
hooks:
# During the ApplicationStop deployment lifecycle event, run the commands
#   in the script specified in "location" starting from the root of the
#   revision's file bundle.
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
# During the BeforeInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/prepare-host.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
# During the ValidateService deployment lifecycle event, run the commands
#   in the script specified in "location".
#  ValidateService:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
