module.exports = function(config){
  config.set({
    basePath : './',
    files : [
        'client/app/libs/angular.min.js',
        'client/app/libs/angular-route.min.js',
        'client/app/libs/angular-resource.min.js',
        'client/app/libs/angular-cookies.min.js',
        'client/app/libs/angular-translate.min.js',
        'client/app/libs/angular-translate-storage-cookie.min.js',
        'client/app/libs/angular-translate-storage-local.min.js',
        'client/app/libs/angular-translate-loader-static-files.min.js',
        'client/app/libs/angular-translate-loader-url.min.js',
        'client/tests/angular-mocks.js',
        'client/tests/mock-gatekeeper.js',
        'client/app/app.js',
        'client/app/navigation/navigation.js',
        'client/app/navigation/*.js',
        'client/app/service_requests/serviceRequest.js',
        'client/app/service_requests/*.js', 
        'client/app/address_service_requests/addressServiceRequest.js',
        'client/app/address_service_requests/*.js',
        'client/app/contact_service_requests/contactServiceRequest.js',
        'client/app/contact_service_requests/*.js',
        'client/app/users/user.js',
        'client/app/users/*.js',
        'client/app/reporting/report.js',
        'client/app/reporting/*.js',
        'client/app/page_count/pageCount.js',
        'client/app/page_count/*.js',
        'client/app/invoices/invoice.js',
        'client/app/invoices/*.js',
        'client/app/utilities/utility.js',
        'client/app/utilities/*.js',
        'client/app/device_management/deviceManagement.js',
        'client/app/device_management/*.js',
        'client/tests/navigation_module_spec.js',
        'client/tests/address_service_request_module_spec.js',
        'client/tests/contact_service_request_module_spec.js'
    ],
    autoWatch : true,
    plugins: ['karma-jasmine', 'karma-phantomjs-launcher','karma-junit-reporter','karma-coverage'],
    port: 9090,
    runnerPort: 9191,
    frameworks: ['jasmine'],
    browsers : ['PhantomJS'],
    singleRun: true,
    reporters: ['progress', 'dots', 'junit', 'coverage'],
    preprocessors: { 'client/app/**/*.js': ['coverage'] },
    coverageReporter: { type : 'cobertura', dir : 'coverage/'},
    junitReporter: {
        outputFile: 'test-results.xml',
        outputDir: '../'
    }

  });
};
